### ISSUE TITLE
脚本启动失败

### ISSUE THREAD

**Issue by nmpassthf** [leonProj/autojs-arknights-ts#2]
- Android版本 7.1.1

- 模拟器 BlueStacks 5.9.0.6502 N64 Hyper-V Version
已启用无障碍和悬浮窗权限
- 输出Log

```
2023-02-01 17:31:27.756/TRACE: 开始运行[/data/user/0/pers.leon.autoark/files/project/./bin/main.node.js]
2023-02-01 17:31:27.895/DEBUG: process exit: 1
2023-02-01 17:31:27.901/ERROR: node:internal/modules/cjs/loader:1185
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: can't find ARM symbol
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/pers.leon.autoark/files/v8/built_in_modules/node_modules/@autojs/opencv/lib/cv4autojs.js:29:34)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
2023-02-01 17:31:27.901/ERROR: Thrown at:
    at Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
2023-02-01 17:31:27.901/ERROR:     at Module.load (node:internal/modules/cjs/loader:981:32)
2023-02-01 17:31:27.901/ERROR:     at Module._load (node:internal/modules/cjs/loader:822:12)
2023-02-01 17:31:27.901/ERROR:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2023-02-01 17:31:27.901/ERROR:     at require (node:internal/modules/cjs/helpers:102:18)
2023-02-01 17:31:27.902/ERROR:     at /data/data/pers.leon.autoark/files/v8/built_in_modules/node_modules/@autojs/opencv/lib/cv4autojs.js:29:34
2023-02-01 17:31:27.902/ERROR:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
2023-02-01 17:31:27.902/ERROR:     at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
```

**Comment by tttleon** [comment]
这个问题不好搞。换个雷电试试
